"""
Django settings for camerasDjango project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@038ob)y64+q24_y0rx=vts_3@2vr9*tv6@$z$_(zlpsa#889&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Configuración de sitios
SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    # django
    'channels',
    'myapp',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'django.contrib.sites',  # Requerido por django-allauth
    'allauth',  # Autenticación principal
    'allauth.account',  # Manejo de cuentas
    'allauth.socialaccount',  # Autenticación social
    'allauth.socialaccount.providers.google',  # Google OAuth
]

SOCIALACCOUNT_PROVIDERS={
    "google": {
        "SCOPE": ["profile", "email"],
    },
    "AUTH_PARAMS": {
        "access_type": "online",
    }
}


# Configuración de redirección después del inicio de sesión
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Configuración de django-allauth
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Django auth
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
)

# Configuración básica para django-allauth
#ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Permitir usuario o email
#ACCOUNT_EMAIL_REQUIRED = True                     # Email obligatorio
#ACCOUNT_USERNAME_REQUIRED = True                  # Username obligatorio
#ACCOUNT_SIGNUP_REDIRECT_URL = '/'                 # Redirección tras registro
#ACCOUNT_LOGIN_REDIRECT_URL = '/'                  # Redirección tras login

# Configuración de email (requerido para validación de cuentas)
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'camerasDjango.urls'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://0.0.0.0:8000",
    "http://192.168.1.3:8000",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["*"]
CORS_ALLOW_HEADERS = ["*"]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'camerasDjango.wsgi.application'
ASGI_APPLICATION = 'camerasDjango.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Cambiar de sqlite3 a mysql
        'NAME': 'people_3',  # El nombre de la base de datos MySQL
        'USER': 'root',  # El usuario para conectarse a MySQL
        'PASSWORD': '',  # La contraseña para el usuario
        'HOST': 'localhost',  # Usar 'localhost' si MySQL está en tu máquina local
        'PORT': '3306',  # Puerto predeterminado para MySQL
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "myapp/static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
